version: '3.8'

services:
#definir un servicio referente a la base de datos 
  db:
    container_name: mongo1
    image: mongo 
    ports:
      - "27018:27017"
    volumes:
      - ./dbdata:/app/dbdata
  server: 
    build: .
    volumes:
      - ./src:/app/src
    command: npm run dev 
    ports:
      - "8001:4000"
    depends_on:
      - db